sudo: required
services:
  - docker

before_install:
  - docker build -t ronithanand/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ronithanand/docker-react npm run test -- --coverage
   #- docker run -e CI=true ronithanand/docker-react npm run test
   #- docker run -e CI=true USERNAME/docker-react npm run test
#deploy:
 # provider: azure_web_apps
  # on: 
  # branch: master
