sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ronithanand/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ronithanand/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'docker'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-460691932461'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

