sudo: required
services:
  - docker

before_install:
  - docker build -t ronithanand/docker-react -f Dockerfile.dev .
script:
  - docker run ronithanand/docker-react npm run test -- --coverage
#deploy:
 # provider: azure_web_apps
  # on: 
  # branch: master
